//页面切换
export const ILLEGAL_ACCESS = 'ILLEGAL_ACCESS';
export const CLOSE_ILLEGAL_ACCESS = 'CLOSE_ILLEGAL_ACCESS';

//登录
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_USERNAME = 'CHANGE_USERNAME';
export const LOG_OUT = 'LOG_OUT';

//查询项目
export const SEARCH_PROJECT = 'SEARCH_PROJECT';
export const CHANGE_KEYWORD = 'CHANGE_KEYWORD';
export const GET_RELATIVE_PROJECTS = 'GET_RELATIVE_PROJECTS';
export const CHANGE_PROJECTPAGE = 'CHANGE_PROJECTPAGE';
export const CHANGE_MOREPROJECT = 'CHANGE_MOREPROJECT';
export const GET_RELATIVE_PROJECTSBYSTATUS = 'GET_RELATIVE_PROJECTSBYSTATUS';

//立项
export const PROJECT_SETUP = 'PROJECT_SETUP';
export const CHANGE_PROJECTID = 'CHANGE_PROJECTID';
export const CHANGE_PROJECTNAME = 'CHANGE_PROJECTNAME';
export const CHANGE_CUSTOMER = 'CHANGE_CUSTOMER';
export const CHANGE_STARTTIME = 'CHANGE_STARTTIME';
export const CHANGE_ENDTIME = 'CHANGE_ENDTIME';
export const CHANGE_MILESTONE = 'CHANGE_MIELSTONE';
export const CHANGE_MAINTECH = 'CHANGE_MAINTECH';
export const CHANGE_BUNIESSFIELD = 'CHANGE_BUNIESSFIELD';
export const CHANGE_MAINFUNCTION = 'CHANGE_MAINFUNCTION';

//项目详细信息
export const PROJECTID_SET = 'PROJECTID_SET';

//修改项目信息
export const CHANGE_MODIFYSTATE = 'CHANGE_MODIFYSTATE';
export const MODIFY_PROJECTINFO = 'MODIFY_PROJECTINFO';
export const MODIFY_PROJECTNAME = 'MODIFY_PROJECTNAME';
export const MODIFY_CUSTOMER = 'MODIFY_CUSTOMER';
export const MODIFY_STARTTIME = 'MODIFY_STARTTIME';
export const MODIFY_ENDTIME = 'MODIFY_ENDTIME';
export const MODIFY_MILESTONE = 'MODIFY_MIELSTONE';
export const MODIFY_MAINTECH = 'MODIFY_MAINTECH';
export const MODIFY_BUNIESSFIELD = 'MODIFY_BUNIESSFIELD';
export const MODIFY_MAINFUNCTION = 'MODIFY_MAINFUNCTION';
export const CHANGE_PUSHSTATE = 'CHANGE_PUSHSTATE';
export const CHANGE_PROJECTSTATE = 'CHANGE_PROJECTSTATE';
export const CHANGE_CHOICE = 'CHANGE_CHOICE';

//管理人员信息
export const MODIFY_MANAGESTATE = 'MODIFY_MANAGESTATE';
export const CHANGE_MANAGEMEMBER = 'CHANGE_MANAGEMEMBER';
export const CREATE_MEMBER = 'CREATE_MEMBER';
export const MODIFY_MEMBER = 'MODIFY_MEMBER';
export const DELETE_MEMBER = 'DELETE_MEMBER';
export const CHANGE_USER_ID = 'CHANGE_USER_ID';
export const CHANGE_SUPERIOR_ID = 'CHANGE_SUPERIOR_ID';
export const CHANGE_ROLES = 'CHANGE_ROLES';
export const CHANGE_PERISSIONS = 'CHANGE_PERMISSIONS';
export const UPDATE_MEMBER = 'UPDATE_MEMBER';
export const GET_MEMBERS = 'GET_MEMBERS';
export const SET_ROLEOPTIONS = 'SET_ROLEOPTIONS';
export const SET_SUPERIOROPTIONS = 'SET_SUPERIOROPTIONS';

//管理功能信息
export const CHANGE_FUNCTIONMANAGE = 'CHANGE_FUNCTIONMANAGE';
export const FUNCTION_MANAGESTATE = 'FUNCTION_MANAGESTATE';
export const CREATE_FUNCTION = 'CREATE_FUNCTION';
export const MODIFY_FUNCTION = 'MODIFY_FUNCTION';
export const DELETE_FUNCTION = 'DELETE_FUNCTION';
export const CHANGE_FUNCTIONDESCRIPTION = 'CHANGE_FUNCTIONDESCRIPTION';
export const SET_FUNCTIONID = 'SET_FUNCTIONID';
export const SET_FUNCTIONSUPERIOR = 'SET_FUNCTIONSUPERIOR';
export const UPDATE_FUNCTION = 'UPDATE_FUNCTION';
export const GET_FUNCTIONS = 'GET_FUNCTIONS';
export const SET_SUPERIORFUNCTIONS = 'SET_SUPERIORFUNCTIONS';
export const CHANGE_UPLOADSTATE = 'CHANGE_UPLOADSTATE';
export const CHANGE_UPLOADDATA = 'CHANGE_UPLOADDATA';
export const CHANGE_DOWNLOADDATA = 'CHANGE_DOWNLOADDATA';

//管理工时信息
export const CHANGE_HOURPAGESTATE = 'CHANGE_HOURPAGESTATE';
export const CHANGE_HOURMODALSTATE = 'CHANGE_HOURMODALSTATE';
export const CREATE_WORKINGHOUR = 'CREATE_WORKINGHOUR';
export const MODIFY_WORKINGHOUR = 'MODIFY_WORKINGHOUR';
export const VERIFY_WORKINGHOUR = 'VERIFY_WORKINGHOUR';
export const SET_WORKINGHOURID = 'SET_WORKINGHOURID';
export const CHANGE_FUNCTIONID = 'CHANGE_FUNCTIONID';
export const CHANGE_ACTIVITY = 'CAHNGE_ACTIVITY';
export const CHANGE_WORKSTARTTIME = 'CHANGE_WORKSTARTTIME';
export const CHANGE_WORKENDTIME = 'CHANGE_WORKENDTIME';
export const CHANGE_VERIFYSTATE = 'CHANGE_VERIFYSTATE';
export const GET_WORKHOURS = 'GET_WORKHOURS';
export const GET_VERIFYHOURS = 'GET_VERIFYHOURS';
export const SET_FUNCTIONHOUROPTIONS = 'SET_FUNCTIONHOUROPTIONS';
export const SET_ACTIVITYOPTIONS = 'SET_ACTIVITYOPTIONS';

//管理项目设备
export const CHANGE_DEVICEPAGE = 'CHANGE_DEVICEPAGE';
export const CHANGE_DEVICEMODAL = 'CHANGE_DEVICEMODAL';
export const TENANCY_DEVICE = 'TENANCY_MODAL';
export const VERIFY_DEVICE = 'VERIFY_DEVICE';
export const RETURN_DEVICE = 'RETURN_DEVICE';
export const SET_DEVICEID = 'SET_DEVICEID';
export const CHANGE_RETURNTIME = 'CHANGE_RETURNTIME';
export const CHANGE_DEVICEMANAGER = 'CAHNGE_DEVICEMANAGER';
export const GET_DEVICE = 'GET_DEVICE';
export const CHANGE_MOREDEVICE = 'CHANGE_MOREDEVICE';
export const CHANGE_CURRENTDEVICEPAGE = 'CHANGE_CURRENTDEVICEPAGE';
export const CHANGE_CURRENTTIME = 'CHANGE_CURRENTTIME';
export const CHANGE_DEVICESTATE = 'CHANGE_DEVICESTATE';

//管理项目风险信息
export const CHANGE_RISKMODAL = 'CHANGE_RISKMODAL';
export const CREATE_RISK = 'CREATE_RISK';
export const CHANGE_RISKTYPE = 'CHANGE_RISKTYPE';
export const CHANGE_RISKDESCRIPTION = 'CHANGE_RISKDESCRIPTION';
export const CHANGE_RISKLEVEL = 'CHANGE_RISKLEVEL';
export const CHANGE_RISKIMPACT = 'CHANGE_RISKIMPACT';
export const CHANGE_RISKCOUNTER = 'CHANGE_RISKCOUNTER';
export const CHANGE_RISKSTATUS = 'CHANGE_RISKSTATUS';
export const CHANGE_RISKTRACK = 'CHANGE_RISKTRACK';
export const CHANGE_RISKPERSON = 'CHANGE_RISKPERSON';
export const GET_RISKS = 'GET_RISKS';
export const GET_PROJECTMEMBERSOPTIONS = 'GET_PROJECTMEMBERSOPTIONS';

//缺陷跟踪
export const GET_URL = 'GET_URL';

//用户信息
export const CHANGE_FAILEDSTATE = 'CHANGE_FAILEDSTATE';
export const CHNAGE_SUCCESSSTATE = 'CHANGE_SUCCESSSTATE';
export const SET_USERNAME = 'SET_USERNAME';
export const SET_USERID = 'SET_USERID';
export const SET_GLOBALROLE = 'SET_GLOBALROLE';

//外部依赖
export const GET_PROJECTSIDS = 'GET_PROJECTSIDS';
export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const GET_BUSINESSFIELDS = 'GET_BUSINESSFIELDS';
export const GET_PERSONNEL = 'GET_PERSONNEL';

//项目内部菜单
export const SWITCH_DETAIL = 'SWITCH_DETAIL';
export const SWITCH_MEMBER = 'SWITCH_MEMBER';
export const SWITCH_FUNCTION = 'SWITCH_FUNCTION';
export const SWITCH_HOUR = 'SWITCH_HOUR';
export const SWITCH_DEVICE = 'SWITCH_DEVICE';
export const SWITCH_RISK = 'SWITCH_RISK';
export const SWITCH_DEFECT  = 'SWITCH_DEFECT';